### ISSUE TITLE
Songs image URL not working

### ISSUE THREAD

**Issue by patelharsh80874** [sumitkolhe/jiosaavn-api#100]
https://c.saavncdn.com/173/GLORY-Hindi-2024-20240827141003-500x500.jpg

Some time is not working with mobile data

![image](https://github.com/user-attachments/assets/aa479c8f-11d0-4949-9428-d540585bdc29)

**Comment by onamkrverma** [comment]
It appears that the Jio server is experiencing an outage today, which may be why the image URL is not functioning.

**Comment by sumitkolhe** [comment]
seems like an issue from jiosaavn's servers. Its working now.
