### ISSUE TITLE
CORS is missing

### ISSUE THREAD

**Issue by Arnav-lunatic** [sumitkolhe/jiosaavn-api#102]
Fetching API in js throwing an error :
`No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
You can refer to a video:
[Access to fetch has been blocked by CORS policy: No 'Access-Control-Allow-Origin' - FIXED!](https://youtu.be/RyH3qu3smVI?si=qAO952olBaTG4B9Q)

**Comment by sumitkolhe** [comment]
this has been fixed in https://github.com/sumitkolhe/jiosaavn-api/releases/tag/v0.0.5
