### ISSUE TITLE
Api is returning 500 internal server error.

### ISSUE THREAD

**Issue by joshi-kt** [sumitkolhe/jiosaavn-api#113]
<img width="1440" alt="Screenshot 2024-11-24 at 11 12 53 PM" src="https://github.com/user-attachments/assets/3d498f6f-447a-4c23-a5e8-6c68b3fafda2">

**Comment by Codersfreedom** [comment]
I am also getting 500 internal server error now.

**Comment by MohammedShameer1532** [comment]
i am also getting 500 internal server error now

**Comment by itsabishiek** [comment]
All the endpoints in saavn.dev returns 500 internal server error now : (

**Comment by Yashveer273** [comment]
"Unexpected token '<', \" <! Document \"... is not valid JSON

**Comment by sumitkolhe** [comment]
This happens sometimes either when jiosaavn.com itself is having issues or when the daily Cloudflare request limit (where saavn.dev is hosted) is exceeded. Closing this issue as this is intermittent and normal
