### ISSUE TITLE
Site returns console info to client

### ISSUE THREAD

**Issue by JarzaClay** [sumitkolhe/jiosaavn-api#18]
When I try to load up the website, instead of showing a webpage, it shows info about the site, without actually showing what is meant to be shown. 
![image](https://user-images.githubusercontent.com/96431656/168583962-971906d7-d939-4ee3-a96f-674d3ba1efdb.png)

**Comment by sumitkolhe** [comment]
That's the home route of the site. Its not a `website`, but rather an api. To learn more please check the documentation - https://docs.saavn.me/

**Comment by JarzaClay** [comment]
Thanks. I assumed that, but that was the site shown on GitHub, so wanted to make sure it wasn't a bug. Thanks!
