### ISSUE TITLE
`captureStream()` from audio Element using Web Audio API : Shows Error

### ISSUE THREAD

**Issue by harshalkaigaonkar** [sumitkolhe/jiosaavn-api#22]
Hey Sumit, 

Not an Issue, but want some Help regarding this.

Great Project, I had an idea to built on same wherin we can stream music in realtime on top of this. (Like [this](https://webrtc.github.io/samples/src/content/capture/video-video/), but audio-audio)
But, there's been an issue bugging me with a process, whenever from an audio tag song is played and try to [capture stream](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream) for the same.
Getting this error : `DOMException: Failed to execute 'captureStream' on 'HTMLMediaElement': Cannot capture from element with cross-origin data`
Is there any way, which supress the CORS error while capturing Stream from Audio Tag?
can also directly, stream from a new server, but want to make it from client side.

Can you help me figure out?

**Comment by sumitkolhe** [comment]
hey @harshalkaigaonkar , did you try setting `crossOrigin="anonymous"` in the audio tag? can you provide any code you've been using, since its hard to debug like this.

**Comment by harshalkaigaonkar** [comment]
Yeah sure.
https://gist.github.com/harshalkaigaonkar/172e39c0b79205e5be134111524454d3.
Have used crossorigin in the media tag.
as the track link redirects to another one, which does not have cors handled on audio side Ig.
is there anything i'm missing?

**Comment by harshalkaigaonkar** [comment]
> Yeah sure. https://gist.github.com/harshalkaigaonkar/172e39c0b79205e5be134111524454d3. Have used crossorigin in the media tag. as the track link redirects to another one, which does not have cors handled on audio side Ig. is there anything i'm missing?

Hey Sumit, have you checked this?

**Comment by sumitkolhe** [comment]
@harshalkaigaonkar i checked it, looks like `cdnsrv.jio.com` has CORS enabled, so even though the apis work fine, the song cannot be streamed directly like the way you're trying to do using just the client side.

**Comment by harshalkaigaonkar** [comment]
Okay, Thanks.
I'll try to use that from Server using buffers or try with setting up a cdn via storage like s3.
