### ISSUE TITLE
Not all songs indexing.

### ISSUE THREAD

**Issue by AnonymousXC** [sumitkolhe/jiosaavn-api#23]
Hi,
When I deployed it to vercel then all the songs were not listing.
If I search for any English Song it was not in the result.
Thanks.
Help ASAP.🙏

**Comment by sumitkolhe** [comment]
On vercel, choose Mumbai as the serverless function region to get all songs

**Comment by AnonymousXC** [comment]
> On vercel, choose Mumbai as the serverless function region to get all songs

Thanks. Working now.😊
