### ISSUE TITLE
Get all songs by an artist.

### ISSUE THREAD

**Issue by AnonymousXC** [sumitkolhe/jiosaavn-api#24]
How to get all songs by an artist.

**Comment by AnonymousXC** [comment]
> @AnonymousXC artists functionality is work in progress. This should be available in the next update

Waiting and working on it.

**Comment by sumitkolhe** [comment]
@AnonymousXC you can get artist's songs and albums now. for more info checkout - https://docs.saavn.me/details/artists/#artist-songs-by-artist-id

**Comment by sumitkolhe** [comment]
Closing this for now, feel free to reopen if needed
