### ISSUE TITLE
API isn't working

### ISSUE THREAD

**Issue by pahadi777** [sumitkolhe/jiosaavn-api#25]
This API isn't working now . Please look into this .

**Comment by AnonymousXC** [comment]
I think they removed the deployment. So, you need to deploy on your server.

**Comment by pahadi777** [comment]
How to deploy it can you help me out ??

**Comment by AnonymousXC** [comment]
I have worked with Vercel so, I can help you to deploy it to Vercel.
So, what are u using for your app?

**Comment by pahadi777** [comment]
Can I get your insta/mail/whatsapp for communication ??

**Comment by r3dm4st3r** [comment]
Any update on this @sumitkolhe

**Comment by AnonymousXC** [comment]
> Can I get your insta/mail/whatsapp for communication ??

Discord :- ANØNYMØÜ$#9330

**Comment by sumitkolhe** [comment]
@r3dm4st3r i'm refactoring the codebase, you can find a WIP deployment at https://saavn.vercel.app, but if you need something stable then either wait a few days or please deploy the main branch on your personal vercel account

**Comment by sumitkolhe** [comment]
@r3dm4st3r the api should be working now at https://saavn.me. Some endpoints have changed, do check out the updated docs at https://docs.saavn.me

**Comment by r3dm4st3r** [comment]
@sumitkolhe awesoem man!  Many new things added, appreciated work.

Meanwhile when your API was under your refactoring, I put my hands on to make one based on laravel.
