### ISSUE TITLE
Heroku Stopped Free service

### ISSUE THREAD

**Issue by KondaShivaradhan** [sumitkolhe/jiosaavn-api#30]
This Custom API won't be working anymore. as Heroku hosting services has terminated free hosting

**Comment by sumitkolhe** [comment]
You can host on vercel instead - https://docs.saavn.me/#host-your-own-instance

**Comment by KondaShivaradhan** [comment]
Hey, thanks for the reply,
how can I fetch all the songs from my custom playlist? where can I get the
Playlist ID
Sample playlist -
https://www.jiosaavn.com/s/playlist/7e8098502f2f6e917c54047e2cd5c7d4/All_Songs/cVix7acO1DLfemJ68FuXsA__
thanks
