### ISSUE TITLE
Is using this API legal?

### ISSUE THREAD

**Issue by codyandersan** [sumitkolhe/jiosaavn-api#32]
I have made a Music PLayer website using this API. I have not put any ads in my website and I do not intend to monetise it in any way.
The API documentation states that this is an unofficial API.
I just want to know whether using this API is **legal** and will I run into any copyright infringement cases by using it?
I had been running my website over Github Pages for few months and I did not face any legal problem till now.

**Comment by sumitkolhe** [comment]
Jio most likely knows about the loopholes in their APIs and still they haven't fixed it for a long time now, so it's on them to fix the issues.
