### ISSUE TITLE
Playlist Details Giving Empty Array Of Songs

### ISSUE THREAD

**Issue by im-ashar** [sumitkolhe/jiosaavn-api#33]
I host my own instance at vercel. When I try to get 
[this with my instance](https://musicmafia.vercel.app/playlists?id=109151306 )
it gives empty array of songs but if I try this with official instance it provides list of songs
[same playlist with saavn.me instance](https://saavn.me/playlists?id=109151306)

**Comment by im-ashar** [comment]
> Where are you hosting your instance? Vercel?

Yes I am hosting on vercel

**Comment by sumitkolhe** [comment]
You'll need to change the serverless function region to.Mumbai in your vercel project settings for it to work properly.
