### ISSUE TITLE
Issue with downloadable links

### ISSUE THREAD

**Issue by samocodes** [sumitkolhe/jiosaavn-api#35]
I guess JioSaavn recently made changes in their API which resulted in breaking the API.

**Comment by sumitkolhe** [comment]
Can you share a sample query or link where you are facing this issue?

**Comment by fmsidoe** [comment]
For example if you use the query:
https://saavn.me/songs?link=https://www.jiosaavn.com/song/hattrick-feat.-yaygo-musalini/IS8beB9ZAmA

You get the results, but the downloadUrl's are not working as the songs were playable yesterday, but today it is not available anymore to play

**Comment by samocodes** [comment]
I tried putting the same method as JioSaavan doing
- Search the song
- Clicks on Searched result 
- Fetches the details of selected result 
- Decrypt Encrypted Track from [this endpoint](https://www.jiosaavn.com/api.php?__call=song.generateAuthToken&url=iPPGVzyogeiPwpro65A0eUaQggN%2B8%2BJ4rPA8VHPBIh7mtXi9KDTyLXZxs2bIgOtiHE4Xq%2Bn52gtHQJ6AF%2FVQIYPzFaL%2FaK97&bitrate=128&api_version=4&_format=json&ctx=web6dot0&_marker=0)
- Above step returns audio url (Need to specify **encrypted url** and **bitrate**).

But there is also a issue with that somehow it wont work from your code or from API Client. I dont know the issue. Tried fake User Agent. Same issue.

**Comment by sumitkolhe** [comment]
i've found the issue, a fix would be live soon

**Comment by sumitkolhe** [comment]
[1df1c0e](https://github.com/sumitkolhe/jiosaavn-api/commit/1df1c0e54abc3ade05647237c4f61875b751fc5d) should fix the download link issue.

**Comment by vibhu1720001** [comment]
When I host it on vercel the search results are only showing hindi songs, while when I locally host it or use saavn.me api it showing worlwide results. How to resolve that?

**Comment by sumitkolhe** [comment]
@vibhu1720001 when deploying on vercel choose the serverless function region as `Mumbai`

**Comment by vibhu1720001** [comment]
Mumbai, India (South)- bom1 option?

**Comment by sumitkolhe** [comment]
Yes

**Comment by vibhu1720001** [comment]
It is showing same results.

**Comment by vibhu1720001** [comment]
Domain should be same right.

**Comment by sumitkolhe** [comment]
you need to deploy again after changing the serverless region

**Comment by vibhu1720001** [comment]
Gotcha

**Comment by vibhu1720001** [comment]
It worked. Thanks.
