### ISSUE TITLE
Download url 

### ISSUE THREAD

**Issue by vibhu1720001** [sumitkolhe/jiosaavn-api#37]
Download url is not working. Can you please check.

**Comment by sumitkolhe** [comment]
Please share the url.

**Comment by vibhu1720001** [comment]
https://aac.saavncdn.com/616/P39KLToZ3OJyaLvfxBX16epxwclrR9vY_320.mp4

**Comment by sumitkolhe** [comment]
@vibhu1720001 @Positive2022 fixed now - https://saavn.me/songs?id=OsolMgGF

**Comment by Positive2022** [comment]
all download url are of 96kbps now @sumitkolhe 

is that expected behaviour or that is also a bug?

**Comment by Positive2022** [comment]
Yup, All good now
Thank you :D
