### ISSUE TITLE
sir pls add playlist by endpoint like 5bvTNvwNiHFuOxiEGmm6lQ__

### ISSUE THREAD

**Issue by SumanBlswas** [sumitkolhe/jiosaavn-api#44]
sir pls add playlist by endpoint like 5bvTNvwNiHFuOxiEGmm6lQ__ this instead of id cause couldn't find id of the playlist

**Comment by sumitkolhe** [comment]
This is implemented now - https://saavn.dev/docs#tag/playlist/get/api/playlists
