### ISSUE TITLE
Lyrics, Plylist

### ISSUE THREAD

**Issue by vineet7800** [sumitkolhe/jiosaavn-api#46]
I checked ana all things works well and thanks for this amazing project, am here because I think there are some issues,

1. Lyrics - it automatically remove all HTML tags from lyrics
2. playlist - playlist not works for all playlist details and also using instance not working and using directly your hosted link works for some means the data fetech for some playlist contain album in json and some don't

**Comment by sumitkolhe** [comment]
1. Thats is on purpose, so as to provide lyrics as string rather than HTML.
2. Please check https://github.com/sumitkolhe/jiosaavn-api#note for some links don't give proper data.
