### ISSUE TITLE
Encrypted Link Decryption technique

### ISSUE THREAD

**Issue by afkcodes** [sumitkolhe/jiosaavn-api#50]
Hey thanks for the amazing work you have done, if possible can you tell me how did you figured out the encryption stuff. I was trying the other day in on of my project so it will be helpful. If you cannot reply here  i will be happy to connect with you over mail or discord.  
discord: afkcodes
mail: ashish2mail9@gmail.com

**Comment by sumitkolhe** [comment]
Answered
