### ISSUE TITLE
How to add limits to api

### ISSUE THREAD

**Issue by ramanveerji** [sumitkolhe/jiosaavn-api#56]
In the readme file, you have added limits to the demo api, how can i add the limit to my api?

**Comment by AkshatGupta-30** [comment]
"https://saavn.dev/api/search/albums?query=$text&page=$page&limit=$limit"
like this

i guess this is what you want

**Comment by ramanveerji** [comment]
> "https://saavn.dev/api/search/albums?query=$text&page=$page&limit=$limit" like this
> 
> i guess this is what you want

No, not like that. I was looking for something so I can set a limit someone for listening or downloading using the api

**Comment by ViSurya** [comment]
> No, not like that. I was looking for something so I can set a limit someone for listening or downloading using the api

do you mean rate limit

**Comment by ramanveerji** [comment]
> 
> > No, not like that. I was looking for something so I can set a limit someone for listening or downloading using the api
> 
> do you mean rate limit 

Maybe yes.

**Comment by sumitkolhe** [comment]
@ramanveerji you can use something like this - https://github.com/rhinobase/hono-rate-limiter
