### ISSUE TITLE
Lyrics Sync

### ISSUE THREAD

**Issue by mr-alhn** [sumitkolhe/jiosaavn-api#62]
How we can sync lyrics ??

**Comment by sumitkolhe** [comment]
@mr-alhn can you explain a bit more what exactly are you trying to achieve?

**Comment by mr-alhn** [comment]
Sir

Right now we are getting the plan text in the lyrics api, how do we sync it with the song?

Like Resso and Spotify, lyrics also play along with the song, same way.

**Comment by sumitkolhe** [comment]
> Sir
> 
> Right now we are getting the plan text in the lyrics api, how do we sync it with the song?
> 
> Like Resso and Spotify, lyrics also play along with the song, same way.

Unfortunately that's out of the scope for this project. It only deals with providing the API to fetch data, usage is upto the developers.

**Comment by mr-alhn** [comment]
Ok thanks
