### ISSUE TITLE
feat: Add API for getting top artists

### ISSUE THREAD

**Issue by tonalmathew** [sumitkolhe/jiosaavn-api#63]
`https://www.jiosaavn.com/api.php?__call=social.getTopArtists`

**Comment by sumitkolhe** [comment]
I'm re-writing the API, this should be included in the update. You can checkout it here - https://github.com/sumitkolhe/jiosaavn-api/tree/dev

**Comment by tonalmathew** [comment]
Okay bro thanks 👍🏻
