### ISSUE TITLE
songs details not fetch by link, id

### ISSUE THREAD

**Issue by Indal-Singh** [sumitkolhe/jiosaavn-api#69]
i think your apis is not working because i try to call this https://saavn.dev/songs?link=https://www.jiosaavn.com/song/tere-sang-ishq-hua-from-yodha/KTAudkRcRkQ

but its showing this type of errors

{
"success": false,
"message": "route not found, check docs at https://saavn.dev/docs"
}

**Comment by sumitkolhe** [comment]
> i think your apis is not working because i try to call this https://saavn.dev/songs?link=https://www.jiosaavn.com/song/tere-sang-ishq-hua-from-yodha/KTAudkRcRkQ
> 
> but its showing this type of errors
> 
> {
> "success": false,
> "message": "route not found, check docs at https://saavn.dev/docs"
> }
> 

Did you check the docs at saavn.dev?

**Comment by Indal-Singh** [comment]
Thanks it's working
