### ISSUE TITLE
Response 500 on songs recommendation

### ISSUE THREAD

**Issue by shahil-yadav** [sumitkolhe/jiosaavn-api#70]
<img width="1231" alt="image" src="https://github.com/sumitkolhe/jiosaavn-api/assets/144932369/547ed56b-7c99-4fe8-bafc-d6bd23e4e8c3">

**Comment by sumitkolhe** [comment]
Looks like something changed from jiosaavn's side, will try to fix this

**Comment by sumitkolhe** [comment]
@shahil-yadav fixed in https://github.com/sumitkolhe/jiosaavn-api/releases/tag/v0.0.3
