### ISSUE TITLE
Artist info error on some artists ids

### ISSUE THREAD

**Issue by shahil-yadav** [sumitkolhe/jiosaavn-api#71]
<img width="1134" alt="Screenshot 2024-03-16 at 10 42 37 AM" src="https://github.com/sumitkolhe/jiosaavn-api/assets/144932369/681a5e20-d178-4e18-9c9d-0c115face910">

**Comment by sumitkolhe** [comment]
@shahil-yadav  seems to be working fine
<img width="1799" alt="Screenshot 2024-03-16 at 11 05 23 AM" src="https://github.com/sumitkolhe/jiosaavn-api/assets/35036894/bee29f2f-630e-4afa-947e-588030491780">

**Comment by sumitkolhe** [comment]
This is now fixed
