### ISSUE TITLE
Search for songs API not working "500 Internal Server Error"

### ISSUE THREAD

**Issue by patelharsh80874** [sumitkolhe/jiosaavn-api#72]
![Screenshot 2024-03-16 111631](https://github.com/sumitkolhe/jiosaavn-api/assets/110234600/fdd0170a-1b3d-437b-bf3a-66c90e109f33)

**Comment by sumitkolhe** [comment]
It is fixed now

**Comment by patelharsh80874** [comment]
Thank you
