### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by sivasoft-cloud** [sumitkolhe/jiosaavn-api#75]
post Release notes
 with version

**Comment by sivasoft-cloud** [comment]
encode that file original metadata possible?

{
          "quality": "12kbps",
          "url": "https://aac.saavncdn.com/091/0d3cfd6080a23f13ace1c38c3296e18f_12.mp4"
        },
        {
          "quality": "48kbps",
          "url": "https://aac.saavncdn.com/091/0d3cfd6080a23f13ace1c38c3296e18f_48.mp4"
        },
        {
          "quality": "96kbps",
          "url": "https://aac.saavncdn.com/091/0d3cfd6080a23f13ace1c38c3296e18f_96.mp4"
        },
        {
          "quality": "160kbps",
          "url": "https://aac.saavncdn.com/091/0d3cfd6080a23f13ace1c38c3296e18f_160.mp4"
        },
        {
          "quality": "320kbps",
          "url": "https://aac.saavncdn.com/091/0d3cfd6080a23f13ace1c38c3296e18f_320.mp4"
        }

**Comment by sumitkolhe** [comment]
it would significantly slow down the api responses and therefore is out of the scope of this project

**Comment by sumitkolhe** [comment]
https://github.com/sumitkolhe/jiosaavn-api/releases/tag/v0.0.2 @sivasoft-cloud release notes will be added alongside new release here onwards

**Comment by sivasoft-cloud** [comment]
Done !
