### ISSUE TITLE
Please correct for playlist url s results

### ISSUE THREAD

**Issue by anirudhanishal** [sumitkolhe/jiosaavn-api#77]
Only 5 results/ 5 files showing but three have more files in playlist results 
Show all results

**Comment by sumitkolhe** [comment]
> Only 5 results/ 5 files showing but three have more files in playlist results 
> Show all results 

Can you share the endpoint you used?

**Comment by anirudhanishal** [comment]
https://saavn.dev/api/playlists?link=https://www.jiosaavn.com/featured/90s-duets-hindi/Icd5-BIRMLpFo9wdEAzFBA__

**Comment by anirudhanishal** [comment]
Please fix this show all files

**Comment by sumitkolhe** [comment]
> Please fix this show all files 

It's open source, you can contribute too 🙂

**Comment by anirudhanishal** [comment]
Ok

**Comment by anirudhanishal** [comment]
Playlist s id  show all results but link show only 5 results please fix

**Comment by sumitkolhe** [comment]
@anirudhanishal this is fixed, you can now pass `page` and `limit` for the playlist by id/link endpoints - https://saavn.dev/docs#tag/playlist/get/api/playlists
