### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by sivasoft-cloud** [sumitkolhe/jiosaavn-api#78]
Fix That home page right side white bar i think scroll bar ! (Desktop View)

**Comment by sumitkolhe** [comment]
Screenshot please

**Comment by sivasoft-cloud** [comment]
![image](https://github.com/sumitkolhe/jiosaavn-api/assets/58784617/6cb94eef-97d0-49aa-96c2-449120b06f58)

**Comment by sivasoft-cloud** [comment]
overflow-y-scroll overflow-x-hidden

**Comment by sumitkolhe** [comment]
> overflow-y-scroll overflow-x-hidden

A PR is welcome :)
