### ISSUE TITLE
Can You add Starter template to deploy this in cloudflare wokers 

### ISSUE THREAD

**Issue by ViSurya** [sumitkolhe/jiosaavn-api#92]
hey i love your work 

and i wanna make an music app using your api but i wanna use cloudflare because cloudflare workers is fast and more cheaper then vercel i try to deploy this on cloudflare but i cant

please can you add cloudflare .toml file to easy deployment

**Comment by sumitkolhe** [comment]
it should work out of the box without needing any configuration, you can try this command to deploy to cloudflare - 

```sh
npx wrangler deploy src/server.ts --name jiosaavn-api --compatibility-date 2024-09-28
```
