### ISSUE TITLE
getting error when try to get artist information

### ISSUE THREAD

**Issue by ratnadeep-naik** [sumitkolhe/jiosaavn-api#96]
i am using following api
https://saavn.dev/api/artists/456323

i am getting followign error:
{
    "success": false,
    "message": "Unexpected token 'M', \"Mohit Chau\"... is not valid JSON"
}

following api also not working
https://saavn.dev/api/artists/458251

**Comment by sumitkolhe** [comment]
both the given calls seem to be working fine, could have been a temporary issue. Closing this now, feel free to reopen it if the issue comes up again.
