### ISSUE TITLE
Returns only 10 songs from a playlist.

### ISSUE THREAD

**Issue by actovisionitsol** [sumitkolhe/jiosaavn-api#97]
Doesn't matter whatever the song count might be, it returns only 10 songs, be it is a playlist or a song from certain artist.

**Comment by onamkrverma** [comment]
The default limit is set to 10. If you need a different number of results, you can adjust the "limit" parameter in your query to the required number.

> https://saavn.dev/api/playlists?id=82914609&limit=20

For more details, refer to the documentation: https://saavn.dev/docs

**Comment by sumitkolhe** [comment]
thanks @onamkrverma !
